import type { LinesDocument } from "../types/lines";
import { pointsToPathData } from "./path-data";

const componentNamePattern = /[^A-Za-z0-9_$]/g;

function sanitizeComponentName(name: string) {
  const compact = name.trim().replace(componentNamePattern, "");

  if (!compact) {
    return "UntitledLines";
  }

  return /^[A-Za-z_$]/.test(compact) ? compact : `Lines${compact}`;
}

export function generateComponentSource(document: LinesDocument): string {
  const componentName = sanitizeComponentName(document.export.componentName);
  const body = document.paths
    .map((path) => {
      const d = pointsToPathData(path.points, path.closed);
      return `      <path d="${d}" fill="${path.fill}" stroke="${path.stroke}" strokeWidth={${
        path.strokeWidth
      } * strokeWidthScale} vectorEffect="non-scaling-stroke" />`;
    })
    .join("\n");

  return `import type { SVGProps } from 'react'

// Generated by lines. Do not edit manually.
export type ${componentName}Props = SVGProps<SVGSVGElement> & {
  strokeWidthScale?: number
}

export function ${componentName}({
  strokeWidthScale = 1,
  ...props
}: ${componentName}Props) {
  return (
    <svg viewBox="0 0 ${document.sourceImage.width} ${document.sourceImage.height}" fill="none" {...props}>
${body || "      {/* Add traced paths in lines */}"}
    </svg>
  )
}
`;
}
